server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: /api
cors:
  allowed-origin: ${FRONTEND_URL:http://localhost:3000}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardsdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
    secret: mysecretkey123456789012345678901234567890
    expiration: 86400000