server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loandb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root  # Use your actual password
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # H2 dialect for Hibernate
    hibernate:
      ddl-auto: update  # or none, validate, create, depending on your needs
    show-sql: true

