spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/
    register-with-eureka: false   # Eureka server does NOT register with itself
    fetch-registry: false         # Eureka server does NOT fetch registry from itself

  server:
    enable-self-preservation: false   # Optional: disable self-preservation for dev/testing